/*
  AUTO-GENERATED by deploy script on 2025-11-19T18:54:12.8777751+03:00
  Do not commit secrets here.
*/
const FIREBASE_CONFIG = {
  apiKey: "REPLACE_WITH_YOUR_FIREBASE_APIKEY",
  authDomain: "ridercms-ced94.firebaseapp.com",
  databaseURL: "https://ridercms-ced94-default-rtdb.firebaseio.com",
  projectId: "ridercms-ced94",
  storageBucket: "ridercms-ced94.firebasestorage.app",
  messagingSenderId: "REPLACE",
  appId: "REPLACE"
};

const API_ENDPOINTS = {
  deposit: "https://deposit-194585815067.europe-west1.run.app",
  collectionQuote: "https://collectionquote-194585815067.europe-west1.run.app",
  collectionPay: "https://collectionpay-194585815067.europe-west1.run.app",
  mpesaCallback: "https://mpesacallback-194585815067.europe-west1.run.app",
  setUserMsisdn: "https://setusermsisdn-194585815067.europe-west1.run.app",
  getSessionByMsisdn: "https://getsessionbymsisdn-194585815067.europe-west1.run.app",
  closeSession: "https://closesession-194585815067.europe-west1.run.app"
};

// Export or attach to window for existing app code
window.FIREBASE_CONFIG = FIREBASE_CONFIG;
window.API_ENDPOINTS = API_ENDPOINTS;
